<?php
/**
 * spl 接口
 */
date_default_timezone_set("PRC");
$array = array("Value1","Value2","Value3");
$outerImplObj = new OuterImpl(new ArrayIterator($array));
foreach($outerImplObj as $k=>$v){
    echo $k .":".$v;
}

class OuterImpl extends IteratorIterator
{
    public function current()
    {
        return parent::current()."_tail"; // TODO: Change the autogenerated stub
    }

    public function key()
    {
       return "Pre".parent::key(); // TODO: Change the autogenerated stub
    }
}